version: "3.8"

services:
  telegram-filter-notifai-base: &telegram-filter-notifai-base
    build: .
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - ./data:/app/data

  telegram-filter-notifai-listen:
    <<: *telegram-filter-notifai-base
    container_name: telegram-filter-notifai-listen
    command: make listen

  telegram-filter-notifai-broadcast:
    <<: *telegram-filter-notifai-base
    container_name: telegram-filter-notifai-broadcast
    command: make broadcast
