FROM python:3.12-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN apt update && apt install -y gcc libffi-dev libssl-dev

ADD . /app
WORKDIR /app

RUN uv sync --frozen

CMD ["uv", "run", "telegram-filter-notifai", "broadcast"]
